<?xml version="1.0" encoding="utf-8"?><Database Name="newzic" Class="NewzicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHRISTOPHE-PC\SQLEXPRESS;Initial Catalog=newzic;Integrated Security=True" SettingsObjectName="Newzic.Core.Properties.Settings" SettingsPropertyName="newzicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Imagem" Member="Imagems">
    <Type Name="Imagem">
      <Column Name="ImagemId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Imagem" Member="ImageFile" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Noticia_Imagem" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comentario" Member="Comentarios">
    <Type Name="Comentario">
      <Column Name="ComentarioId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Jornalista_Comentario" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
      <Association Name="Noticia_Comentario" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jornalista" Member="Jornalistas">
    <Type Name="Jornalista">
      <Column Name="Nome" Type="System.String" DbType="NChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Jornalista_Comentario" Member="Comentarios" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Comentario" />
      <Association Name="Jornalista_Administrador" Member="Administrador" ThisKey="JornalistaId" OtherKey="AdministradorId" Type="Administrador" Cardinality="One" />
      <Association Name="Jornalista_Moderador" Member="Moderador" ThisKey="JornalistaId" OtherKey="ModeradorId" Type="Moderador" Cardinality="One" />
      <Association Name="Jornalista_Banido" Member="Banidos" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Banido" />
      <Association Name="Jornalista_VotoNoticia" Member="VotoNoticias" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="VotoNoticia" />
      <Association Name="Jornalista_Noticia" Member="Noticias" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Noticia" />
      <Association Name="Jornalista_Queixa" Member="Queixas" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Queixa" />
      <Association Name="Jornalista_Sessao" Member="Sessao" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Sessao" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Video" Member="Videos">
    <Type Name="Video">
      <Column Name="VideoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Noticia_Video" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Administrador" Member="Administradors">
    <Type Name="Administrador">
      <Column Name="AdministradorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Jornalista_Administrador" Member="Jornalista" ThisKey="AdministradorId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Moderador" Member="Moderadors">
    <Type Name="Moderador">
      <Column Name="ModeradorId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Jornalista_Moderador" Member="Jornalista" ThisKey="ModeradorId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banido" Member="Banidos">
    <Type Name="Banido">
      <Column Name="BanidoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DataFim" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Permanente" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Jornalista_Banido" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VotoNoticia" Member="VotoNoticias">
    <Type Name="VotoNoticia">
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Jornalista_VotoNoticia" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
      <Association Name="Noticia_VotoNoticia" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NoticiaFlagged" Member="NoticiaFlaggeds">
    <Type Name="NoticiaFlagged">
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Noticia_NoticiaFlagged" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Noticia" Member="Noticias">
    <Type Name="Noticia">
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Corpo" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Pontuacao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FlagCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Marked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Noticia_Imagem" Member="Imagems" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Imagem" />
      <Association Name="Noticia_Comentario" Member="Comentarios" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Comentario" />
      <Association Name="Noticia_Video" Member="Videos" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Video" />
      <Association Name="Noticia_VotoNoticia" Member="VotoNoticias" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="VotoNoticia" />
      <Association Name="Noticia_NoticiaFlagged" Member="NoticiaFlaggeds" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="NoticiaFlagged" />
      <Association Name="Noticia_Mapa" Member="Mapas" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Mapa" />
      <Association Name="Jornalista_Noticia" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Queixa" Member="Queixas">
    <Type Name="Queixa">
      <Column Name="QueixaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AcusadoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Texto" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Resolved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Assunto" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Jornalista_Queixa" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sessao" Member="Sessaos">
    <Type Name="Sessao">
      <Column Name="Token" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="JornalistaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Jornalista_Sessao" Member="Jornalista" ThisKey="JornalistaId" OtherKey="JornalistaId" Type="Jornalista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="TourId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MapaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Morada" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="Mapa_Tour" Member="Mapa" ThisKey="MapaId" OtherKey="MapaId" Type="Mapa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mapa" Member="Mapas">
    <Type Name="Mapa">
      <Column Name="MapaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoticiaId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Morada" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Latidude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="isTour" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Mapa_Tour" Member="Tours" ThisKey="MapaId" OtherKey="MapaId" Type="Tour" />
      <Association Name="Noticia_Mapa" Member="Noticia" ThisKey="NoticiaId" OtherKey="NoticiaId" Type="Noticia" IsForeignKey="true" />
    </Type>
  </Table>
</Database>